### ISSUE TITLE
Custom decoration that looks & feels the same on all windows version ?

### ISSUE THREAD

**Issue by IMAN4K** [oberth/custom-chrome#1]
Hi @oberth 
Thanks for the great samples.
There're some window out there that has a native AND custom look on all windows version like [this one](https://github.com/telegramdesktop/tdesktop/blob/v0.5.0/Telegram/SourceFiles/pspecific_wnd.cpp) (the source is little complicated)
![custom_frame](https://cloud.githubusercontent.com/assets/16017595/24838505/611abf60-1d5e-11e7-9be6-d7bf6a224d8c.png)

And these sort of window could be resize outside of window frame plus all other native windows features (Aero shake, Shadow, minimize animation)
could you help me to find the logic behind these type of window frame ?
I know this is a lot of work but i want to have the right start point to do that and publish final result to others and fill this hole !

**Comment by melak47** [comment]
The title bar and buttons are completely custom drawn, so I'm not sure what you mean with "native AND custom look".
The telegram window, unlike a plain `WS_OVERLAPPEDWINDOW` window, can also be resized above the top of the custom drawn fake title bar. If you inspect the window with Spy++, you'll find it uses a `WS_POPUP` derived style with `WS_THICKFRAME` and friends to enable the aero functionality.

You'll also find a number of additional windows titled TelegramShadow0, TelegramShadow1, and so on, which extend beyond the edges of the visible main window. These are likely set up to act as the invisible resize borders.

**Comment by IMAN4K** [comment]
> The title bar and buttons are completely custom drawn, so I'm not sure what you mean with "native AND custom look".

Native + Custom = Having native features (Aero shake + minimize animation ,...) while looks like custom drawn maybe should be `native features` + `custom look` !

Also it seems there are two window (when minimize):
![1](https://cloud.githubusercontent.com/assets/16017595/25243827/a961c616-2613-11e7-9e67-0d99cb7a65bd.png)
![2](https://cloud.githubusercontent.com/assets/16017595/25243834/ae78b7fe-2613-11e7-8c48-fc8b1a1c60e6.png)
![3](https://cloud.githubusercontent.com/assets/16017595/25243840/b3a26914-2613-11e7-9bdb-f7445ada1aae.png)
![4](https://cloud.githubusercontent.com/assets/16017595/25243844/b889c328-2613-11e7-9004-0004b364c49f.png)
And if we look at the source we can find that shadows are custom drawn using `GdiPlus`
So i was wonder if you could help me to find the idea behind that source to start implement...
